service: humidori
plugins:
  - serverless-finch
custom:
  client:
    bucketName: humidori
provider:
  name: aws
  runtime: nodejs6.10
  profile: jari
  region: eu-central-1
  environment:
    HUMIDOR_TABLE: humidor
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
      Resource: arn:aws:dynamodb:*:*:table/humidori
functions:
  weather:
    handler: getHumidorDataLambda.get
    events:
      - http: GET humidori
    memorySize: 128
    timeout: 10
